### ISSUE TITLE
Static ContainerController @ArquillianResource inject resource

### ISSUE THREAD

**Issue by galderz** [infinispan/infinispan-arquillian-container#33]
Would it be possible to have injected `ContainerController` as a static field? e.g.

```
@ArquillianResource
static ContainerController controller;
```

The advantage of doing this is that you'd be able to access it in `@BeforeClass` and `@AfterClass` callbacks, tweaking container configuration and starting the container once for all tests in that class. In `@AfterClass`, you'd revert the changes.

Is that possible?

**Comment by galderz** [comment]
If you try to do this, you get an NPE when you access static controller in `@BeforeClass` callback.

I've also tried having controller non-static, and trying to access it in `@Before`, and I got:

```
java.lang.IllegalArgumentException: No deployment scenario in context
	at org.jboss.arquillian.container.test.impl.client.container.ClientContainerController.start(ClientContainerController.java:68)
	at org.infinispan.tutorial.remote.compatibility.RemoteCompatibilityIT.startCustomContainer(RemoteCompatibilityIT.java:60)
```

**Comment by mgencur** [comment]
Hi Galder, AFAIK, this was supposed to be fixed as part of https://issues.jboss.org/browse/ARQ-271. It doesn't seem to be implemented yet. That's all I know.

**Comment by smiklosovic** [comment]
@galderz @mgencur 

I think you could workaround it ... 

You have to write your own extension and register an observer which @Observes BeforeClass with some negative precedence (like Integer.MIN_VALUE or something) to be sure that all you want to inject is indeed already created. This observer will treat that event as the last one so you can be sure that ContainerController which was created somewhere in BeforeClass exists (assuming that ContainerController's InstanceProducer is @ClassScoped).

Then you do not use @ArquillianResource annotation but your own in your test, like @GiveMeContainerController private static ContainerController controller; and you basically enrich it yourself there.

Example here 

https://github.com/TadeasKriz/arquillian-osmium/blob/master/arquillian-osmium-container/src/main/java/org/arquillian/osmium/OsmiumLifecycleManager.java#L54-L70

what that effectively does that it injects 

@OsmiumResource private static OsmiumBuilder builder; in BeforeClass

**Comment by smiklosovic** [comment]
here you go

https://github.com/arquillian/arquillian-core/blob/master/container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/client/container/ContainerContainerControllerCreator.java

that ContainerController is done as ApplicationScoped which means it will be available anytime, and it is produced BeforeSuite which is stage before BeforeClass so I think you are super safe to inject it statically as suggested in my previous post.

**Comment by smiklosovic** [comment]
or maybe you want this one?

https://github.com/arquillian/arquillian-core/blob/master/container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/client/container/ClientContainerControllerCreator.java

SetupContainers event is fired somewhere in BeforeClass so you have to apply that negative precendece in your own enricher to be sure that in time you observe BeforeClass event that ContainerController was already created hence you Inject<ContainerController> and statically enrich that field.

I do not know what is the difference between them, maybe @mgencur could provide his expetise since he wrote that.

**Comment by smiklosovic** [comment]
you hit that Deployment scenario null exception because DeploymentScenario is produced as ClassScoped and when you wan to use it in BeforeClass, my guess is that ClassContext is not active hence it is not injected hence it is null. 

https://github.com/arquillian/arquillian-core/blob/4b388320fadee67e8630004628f6f3a9aa8d27b7/container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/client/deployment/DeploymentGenerator.java#L63-L64

**Comment by smiklosovic** [comment]
@galderz 

I write that extension for you https://github.com/smiklosovic/arquillian-static-container-controller

**Comment by smiklosovic** [comment]
it was moved here https://github.com/arquillian/arquillian-showcase/tree/master/extensions/arquillian-static-container-controller

**Comment by mgencur** [comment]
As @smiklosovic described, this is now available as part of the other project. Thanks @smiklosovic .
Apart from that, Infinispan Arquillian provides @WithRunningServer annotation (https://github.com/infinispan/infinispan-arquillian-container/blob/master/infinispan-impl/src/main/java/org/infinispan/arquillian/core/WithRunningServer.java) which makes it possible to start containers in "before class" phase.
